### ISSUE TITLE
Newline in output

### ISSUE THREAD

**Issue by MarvNC** [iamjustkoi/StudyTimeStats#21]
Thanks a ton for developing this awesome update, it's amazing to see all this customization available to the user. I was wondering, is there a way to put newlines in the text displaying the stats?
![anki_User_1_-_Anki_2023-05-26_21-39-30](https://github.com/iamjustkoi/StudyTimeStats/assets/17340496/d8ca7d5e-0935-4ce8-b632-6e86f7ab3b66)

**Comment by iamjustkoi** [comment]
> Thanks a ton for developing this awesome update, it's amazing to see all this customization available to the user.

You bet, happy you're liking it! ^^

> is there a way to put newlines in the text displaying the stats?

Yep, there's actually a couple ways to achieve this! Since the output from the textbox is read in HTML, you can use any HTML elements you want there and it should format it, respectively, when displaying it on the main window!

So, for your current setup, you could try something like:

`%total_hrs </br> %total_rev` for the "Total" output and
`%range_hrs </br> %range_rev` for the "Past 2 Weeks" output (assuming you're using range time here)

Or, if you want, you can also mess around with the stat view's HTML itself from the code expandable
(the little `</>` icon at the bottom right).
With that the formatting options are pretty open-ended, but you'd probs still want to do something similar to the above, but replacing `{{Output}}` with `%total_hrs </br> %total_rev`, etc., instead.

Hope that helps!
