### ISSUE TITLE
What macro counts the hours studied in this week?

### ISSUE THREAD

**Issue by darlopvil** [iamjustkoi/StudyTimeStats#30]
Hello, 

so I want to show how many hours I've studied this current week in the stats but I'm not sure what's the difference between this 2 options:
![imagen](https://github.com/iamjustkoi/StudyTimeStats/assets/60988792/83d86fde-0c4f-4ecf-8805-f42d67959be7)

**Comment by iamjustkoi** [comment]
Hey! 
> what's the difference between this 2 options

Yeah, I felt like the wording could get a little confusing, to be honest. 

Tried copying some other common wording formats, but it pretty much follows this sort of pattern:
- `previous` - the "previous" range, or the one that came before the current one (e.g. last week and not *this* week)
- `past` - the "past" of the current range (i.e. elapsed range time, or a past and not future/present time)

Hopefully that helps out a bit!

**Comment by darlopvil** [comment]
> elapsed range time, or a past and not future/present time

Hello again, so, there isn't a way to show what i want?
%week_hrs shows only 3 hours, when I did more than that only on Monday. 

I don't know how exactly work these macros.

**Comment by iamjustkoi** [comment]
Hi again!

> there isn't a way to show what i want?

Um, hmm, honestly it depends on how you've set up other parts of the options, and if you're looking for "time from __ day" vs "time from the last ___ days". 

For reference: 
- `%week_hrs` gives you the time studied over the last 7 days
- And `%range_hrs` will give you the time studied over the last range-time 
  - (e.g. a range set to "Calendar Week" with the "Week-Start Day" set to Monday will output the total study time since Monday, etc.).

If not that, then the "Default" deck is also disabled by default in the `Advanced` tab, so you might want to check if anything's disabled there and see if enabling it might help, too.

Other than that, it could be a number of other things and you may want to post a screenshot of your settings, or upload the meta.json (Tools -> Add-ons -> Study Time Stats -> View Files), and that might help out a bit with figuring out what you're sorta going for.

**Comment by darlopvil** [comment]
General tab screenshot:
![imagen](https://github.com/iamjustkoi/StudyTimeStats/assets/60988792/7a012ed9-b438-4854-b0f3-f8bb35df6e84)

Advanced tab screenshot:
![imagen](https://github.com/iamjustkoi/StudyTimeStats/assets/60988792/e062a1bf-b9d2-488a-acbd-e88f887983db)
(Every deck is enabled)

Result:
![imagen](https://github.com/iamjustkoi/StudyTimeStats/assets/60988792/aa2168dd-9f0d-434e-8abc-260c542f4b01)

meta.json: https://anonfiles.com/Pbpeo4w2z1/meta_json

As you can see, there's only 2 parameters here. Time in hours studied over the last week and, time studied this current week. No one shows correctly the values.

**Comment by iamjustkoi** [comment]
Hey, sorry the reply's a little delayed!

So, with the "Last Week" view, you might want to be using `%prev_range_hrs`, instead,  (if you're going for the previous Monday-Sunday times).

Also, looks like you do actually have 1 deck disabled still, weirdly! (Default deck, but it might be a different name for you). Can't tell if it's intentional or not from the screenshot, might be off-screen and needs to be scrolled down to, but if no deck's are grayed out when you open the window, defs let me know! 

You can also manually enable the deck by opening the `meta.json` file and removing the `1` at `Excluded_Deck_Ids: [1]`.

Other than that, it might depend on what your current next-day hour is in Anki, too, depending on when ya studied, pretty much.

(Also gonna attach a zipped meta.json file here with the `%prev_range_hrs` and `Excluded_Deck_IDs` edits already done, hope it helps!)

[meta.zip](https://github.com/iamjustkoi/StudyTimeStats/files/11734570/meta.zip)

**Comment by darlopvil** [comment]
Not personal, but at this point I'm losing my faith in this. Nothing works. Yesterday (Monday) i did 45 mins of reviewing and the addon says 0 mins. Honestly, I'm tired of trying everything, checking-unchecking and testing...

This is how i finally let it:

![imagen](https://github.com/iamjustkoi/StudyTimeStats/assets/60988792/9cfdec26-47bc-4aa2-b2ac-bd74d8299978)
![imagen](https://github.com/iamjustkoi/StudyTimeStats/assets/60988792/7cee7527-f741-4749-a359-d0d09816739f)
![imagen](https://github.com/iamjustkoi/StudyTimeStats/assets/60988792/53cc4d9d-f9d5-410a-86e6-06a9328f8b40)

>  looks like you do actually have 1 deck disabled still, weirdly! (Default deck

yeah, i thought it was deleted. Anyway, i don't use it.

**Comment by iamjustkoi** [comment]
Oh shoot, now I can understand the confusion. 

I forgot that I'd coded it a long while ago to have it be that the Week-Start day is the day times are initialized instead of refreshed for the week-range times, specifically.

In other words, if you want to have "Monday" be the start of your week, you'll actually want to put "Sunday" right now, unfortunately. (`Monday = Sunday`, `Sunday = Saturday`, etc.) See if that might work better for you.

I can try and push an update to fix that back to how it was originally intended as soon as I'm able.

> Not personal, but at this point I'm losing my faith in this.

Yeah, sorry, some the code is a little dated from my current standards too, but I appreciate the patience, either way!

**Comment by darlopvil** [comment]
Well, "This week" stat now works correctly, so that's some good news finally. However, i'm not very sure about how to specifically create "Last Week". It's kind of weird when always the same number of hours appear either i choose `%prev_week_hrs` or `%prev_range_hrs`. Indeed, may i touch "Past week" in the "Selected Range" field? I'ts kind of confusing tbh.

Thanks for your fast reply btw.

**Comment by darlopvil** [comment]
Hi again,

I'd already set the first day of the week to Sunday, but i'm not really sure if over 5h was really the exact amount of time i studied the week before. I'm gonna test this feature in the addon for the current week. Let's see on next Monday if the Sun-Monday workaround really helped me.

Thanks 🤝

**Comment by darlopvil** [comment]
Hello, what's up.

As mentioned before, 1 week already finished, so i'm here to announce that with the last small fixes done, the stats seem to work properly now. 

Thanks for your hard work and patience 🤝

**Comment by iamjustkoi** [comment]
Hey again!

>As mentioned before, 1 week already finished, so i'm here to announce that with the last small fixes done, the stats seem to work properly now.

Appreciate the follow up, really happy to hear it's working for you now! 

> Thanks for your hard work and patience 🤝

No prob, thanks for sticking through it with me, too! 
Happy studies! 😄
